### ISSUE TITLE
WSGI example could provide data similar to LibreHardwareMonitor

### ISSUE THREAD

**Issue by snip3rnick** [snip3rnick/PyHardwareMonitor#4]
The wsgi example currently delivers a full dump of the `HardwareMonitor.Hardware.Computer` object tree as much as possible.  
A request has been made to generalize and convert the structure to make the output closer or equal to the LibreHardwareMonitor web server (mentioned in #2).

**Comment by snip3rnick** [comment]
The output is now nearly identical to the LibreHardwareMonitor GUI server, except for the `ImageURL` fields existing yet not being set to anything

**Comment by LRF520** [comment]
> The output is now nearly identical to the LibreHardwareMonitor GUI server, except for the `ImageURL` fields existing yet not being set to anything

The "images_icons" URL names are very important,because they are key fields used to distinguish different hardware, it is recommended that the code of librehardwaremonitor be written as fixed parameters, so as to help filter dynamic data. I can't understand the code of librehardwaremonitor. I consulted the author of librehardwaremonitor, but no one answered this question. This is the link to my question:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/804#issue-1353248019
![image](https://user-images.githubusercontent.com/58470642/189258104-2f7d2d91-5222-4d5a-8fad-f21c33f53583.png)

Two parameters are currently determined, namely:



(1) The "images_icons" name of Intel integrated graphics card is "Intel. png";



(2) The "images_icons" name of NVIDIA independent graphics card is "nvidia. png"；




Four parameters are uncertain, because I can't understand those codes:



(1) The "images_icons" name of AMD integrated graphics card?



(2) The "images_icons" name of AMD independent graphics card?



(3) The "images_icons" name of ATI integrated graphics card?



(4) The "images_icons" name of the ATI independent graphics card?

**Comment by snip3rnick** [comment]
The image icon paths are literally just a mapping from `x.Hardware.HardwareType` to images.
There is **no** distinction between *AMD* and *ATI* or *integrated* and *dedicated* in the [original server code](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitor/Utilities/HttpServer.cs#L622).  
With an *AMD* card you would even get the **ati.png** image which can not be useful information.

I am afraid the only way to properly differentiate them is by looking at hardware names and driver descriptions.

**Comment by snip3rnick** [comment]
Closing the issue since the requested data can not be provided by LibreHardwareMonitor
